import { FIELD_MAP } from './config.js'

// Returns { ok: bool, errors: string[], warnings: string[] }
export function validateTeamSeasons(teamSeasons, targetMode = 'raw') {
  const errors   = []
  const warnings = []

  if (!Array.isArray(teamSeasons) || teamSeasons.length === 0) {
    return { ok: false, errors: ['teamSeasons must be a non-empty array'], warnings }
  }

  // Required predictor columns
  const REQUIRED_PRED = [
    FIELD_MAP.off_eFG, FIELD_MAP.off_TOV, FIELD_MAP.off_ORB, FIELD_MAP.off_FTR,
    FIELD_MAP.def_eFG, FIELD_MAP.def_TOV, FIELD_MAP.def_ORB, FIELD_MAP.def_FTR,
  ]

  // Required target columns per mode
  const REQUIRED_TGT = targetMode === 'adjusted'
    ? [FIELD_MAP.adjOE, FIELD_MAP.adjDE]
    : [FIELD_MAP.rawOE, FIELD_MAP.rawDE]

  const REQUIRED_CONV = [FIELD_MAP.ftPct]  // needed for EPA conversion

  const allRequired = [...REQUIRED_PRED, ...REQUIRED_TGT, ...REQUIRED_CONV]

  // Column presence check on first row
  const first = teamSeasons[0]
  const missing = allRequired.filter(col => !(col in first))
  if (missing.length > 0) {
    errors.push(`Missing required columns: ${missing.join(', ')}`)
    return { ok: false, errors, warnings }
  }

  // Adjusted/raw mismatch detection
  if (targetMode === 'adjusted') {
    warnings.push(
      'Target mode is "adjusted" (adjoe/adjde) but predictors are raw four factors. ' +
      'Coefficients will absorb opponent-strength effects. ' +
      'Use targetMode="raw" to avoid this mismatch.'
    )
  }

  // Count valid rows (no NaN/null in required fields)
  let validCount = 0
  const seenKeys = new Set()
  for (const ts of teamSeasons) {
    const key = `${ts.school}__${ts.year}`
    if (seenKeys.has(key)) {
      warnings.push(`Duplicate team-season detected: ${key}`)
    }
    seenKeys.add(key)

    const vals = allRequired.map(col => ts[col])
    if (vals.every(v => v != null && !Number.isNaN(Number(v)))) validCount++
  }

  const n = validCount

  if (n < 10) {
    errors.push(`Only ${n} valid observations — minimum 10 required`)
    return { ok: false, errors, warnings }
  }

  // Numeric type check (spot-check first 5 rows)
  for (const col of allRequired) {
    const nonNumeric = teamSeasons.slice(0, 5).filter(ts => {
      const v = ts[col]
      return v != null && Number.isNaN(Number(v))
    })
    if (nonNumeric.length > 0) {
      errors.push(`Column "${col}" has non-numeric values in first 5 rows`)
    }
  }

  return { ok: errors.length === 0, errors, warnings, validCount: n }
}

// Filter to rows with no missing values across the given column list
export function filterValidRows(teamSeasons, cols) {
  return teamSeasons.filter(ts =>
    cols.every(col => ts[col] != null && !Number.isNaN(Number(ts[col])))
  )
}

// Verify game log rows for Tier 2
export function validateGameLogs(gameLogs, { ivyOnly = false } = {}) {
  const warnings = []

  if (!Array.isArray(gameLogs) || gameLogs.length === 0) {
    return { ok: false, errors: ['gameLogs is empty or missing'], warnings, synthetic: true }
  }

  const rows = ivyOnly ? gameLogs.filter(g => g.is_ivy_opponent) : gameLogs

  // Check for synthetic marker field (generated by generate-mock-gamelogs.mjs)
  const hasSyntheticSignal = gameLogs.every(g =>
    g.school && ['princeton','yale','harvard','columbia','penn','brown','dartmouth','cornell']
      .includes(g.school)
  )

  // A real Barttorvik game-log would include game_id or source fields
  const hasRealSourceField = gameLogs.some(g => g.game_id || g.source)

  const isSynthetic = hasSyntheticSignal && !hasRealSourceField

  if (isSynthetic) {
    warnings.push(
      'SYNTHETIC DATA: game logs appear to be generated by generate-mock-gamelogs.mjs. ' +
      'Tier 2 EPA weights are NOT validated. Replace gameLogs.json with real Barttorvik data.'
    )
  }

  if (rows.length < 20) {
    return {
      ok: false, synthetic: isSynthetic,
      errors: [`Only ${rows.length} rows (need ≥20)${ivyOnly ? ' — try unchecking Ivy-only' : ''}`],
      warnings,
    }
  }

  return { ok: true, errors: [], warnings, synthetic: isSynthetic, validCount: rows.length }
}
